config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {:registrations => "registrations"}

  devise_scope :user do
    post "/register_user" => "registrations#create"
  end

  as :user do
    get "/register", to: "registrations#new", as: "register"
  end

  resources :customers
  resources :employees
  resources :services
  resources :attendances

  resources :rescue_requests do
    get 'answer', to: 'rescue_requests#answer'
  end

  root to: 'home#index'
  get '/dashboard', to: 'pages#dashboard'
  get '/search', to: 'customers#searchpage'
  post '/search', to: 'customers#search'
  get '/ban', to: 'pages#ban'
  post '/ban', to: 'pages#destroy_user'
  get '/schedule', to: 'attendances#schedule'

  post '/register_user', to: 'registrations#create'
end

app/models/service.rb
class Service < ApplicationRecord
  has_and_belongs_to_many :employees

  validates :name, presence: true
end

app/controllers/services_controller.rb
# rubocop: disable Metrics/ClassLength

class ServicesController < ApplicationController
  before_action :set_service, only: %i[edit show update]
  skip_before_action :verify_authenticity_token, only: :search

  def index
    @services = Service.order('name ASC')
  end

  def new
    flash[:alert] = ''
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)

    if @service.save
      redirect_to @service
    else
      flash[:alert] = 'Não foi possível salvar. Verifique todos os campos!'
      render :new
    end
  end

  def show; end

  def edit
    flash[:alert] = ''
  end

  def update
    if @service.update(service_params)
      redirect_to services_path
    else
      flash[:alert] = 'Não foi possível salvar. Verifique todos os campos!'
      render :edit
    end
  end

  private

  def set_service
    @service ||= Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit!
  end
end

app/views/services/edit.html.erb
<div class="customer-form">

  <h3>Alterar nome do serviço</h3>
  <% unless flash[:alert].empty? %>
    <div class="deep-orange-text text-darken-3 deep-orange lighten-4 warning"><%= flash[:alert] %></div>
  <% end %>

  <%= form_for @service do |form| %>

    <div class="row customer-form__row">
      <p class="input-field">
        <%= form.text_field :name, placeholder: "Nome" %>
        <%= form.label :name, "Nome" %>
      </p>
    </div>

    <div class="center-align">
      <%= form.submit 'Salvar', class: 'red lighten-1 btn-large' %>
    </div>
  <% end %>
</div>


<script>
  $(document).ready(function(){
    $('.datepicker').datepicker();
  });
</script>

app/views/services/index.html.erb
<div class="section no-pad-bot" id="index-banner">
  <h2 class="header center indigo-text text-darken-4">Serviços</h2>
</div>

<% if current_user.admin? %>
<div style="display: flex;">
  <a href="<%= new_service_path %>"style="margin: auto; margin-bottom: 24px;" class="red lighten-1 btn">Novo Serviço</a>
</div>
<% end %>

<div class="collection">
  <% @services.each do |service|  %>
    <a href="<%= edit_service_path(service.id) %>" class="collection-item"><%= service.name %></a>
  <% end %>
</div>

app/views/services/new.html.erb
<div class="customer-form">

  <h3>Cadastrar Serviço</h3>
  <% unless flash[:alert].empty? %>
    <div class="deep-orange-text text-darken-3 deep-orange lighten-4 warning"><%= flash[:alert] %></div>
  <% end %>

  <%= form_for @service do |form| %>

    <div class="row customer-form__row">
      <p class="input-field">
        <%= form.text_field :name, placeholder: "Nome" %>
        <%= form.label :name, "Nome" %>
      </p>
    </div>

    <div class="center-align">
      <%= form.submit 'Cadastrar', class: 'red lighten-1 btn-large' %>
    </div>
  <% end %>
</div>


<script>
  $(document).ready(function(){
    $('.datepicker').datepicker();
  });
</script>

app/views/services/show.html.erb
<div class="customer-details">
  <div class="row">
    <div class="col s6">
      <h2><%= @service.name %></h2>

      <div class="">
        <% if current_user&.admin? %>
          <%= link_to 'Alterar', edit_service_path(@service), class: "indigo lighten-1 btn-small" %>
        <% end %>
        <%= link_to 'Voltar', services_path %>
      </div>
    </div>
  </div>
</div>