config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {:registrations => "registrations"}

  devise_scope :user do
    post "/register_user" => "registrations#create"
  end

  as :user do
    get "/register", to: "registrations#new", as: "register"
  end

  resources :customers
  resources :employees
  resources :services
  resources :attendances

  resources :rescue_requests do
    get 'answer', to: 'rescue_requests#answer'
  end

  root to: 'home#index'
  get '/dashboard', to: 'pages#dashboard'
  get '/search', to: 'customers#searchpage'
  post '/search', to: 'customers#search'
  get '/ban', to: 'pages#ban'
  post '/ban', to: 'pages#destroy_user'
  get '/schedule', to: 'attendances#schedule'

  post '/register_user', to: 'registrations#create'
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_and_belongs_to_many :services

  validates :name, :phone, :document, presence: true

  enum gender: { male: 0, female: 1, other: 2 }
  enum status: { active: 0, vacation: 1, deactivated: 2 }

  scope :by_gender, ->(param) { where(gender: param) }

  validate :employee_has_service

  def employee_has_service
    if self.services.blank?
      errors.add(:base, 'É necessário adicionar pelo menos um serviço')
    end
  end
end

app/controllers/employees_controller.rb
# rubocop: disable Metrics/ClassLength
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[edit show update]
  skip_before_action :verify_authenticity_token, only: :search

  def index
    @employees = Employee.active.order('name ASC')
    @deactivated_employees = Employee.deactivated.order('name ASC')
    @vacation_employees = Employee.vacation.order('name ASC')
  end

  def new
    flash[:alert] = ''
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)

    @employee.services = params[:service_id] ? params[:service_id].map { |a| Service.find(a) } : []

    if @employee.save
      redirect_to @employee
    else
      custom_alert
      render :new
    end
  end

  def show
  end

  def edit
    @services = @employee.services.map(&:id) || []
    flash[:alert] = ''
  end

  def update
    @services = @employee.services.map(&:id) || []

    @employee.services = params[:service_id] ? params[:service_id].map { |a| Service.find(a) } : []

    if @employee.update(employee_params)
      redirect_to @employee
    else
      custom_alert
      render :edit
    end
  end

  private

  def custom_alert
    if @employee.errors[:base].blank?
      flash[:alert] = 'Não foi possível salvar. Verifique todos os campos!'
    else
      flash[:alert] = @employee.errors[:base].join(", ")
    end
  end

  def set_employee
    @employee ||= Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit!
  end
end
# rubocop: enable Metrics/ClassLength

app/views/employees/edit.html.erb
<div class="employee-form">

  <h3>Atualizar cadastro de Funcionário</h3>
  <% unless flash[:alert].empty? %>
    <h6 class="deep-orange-text text-darken-3 deep-orange lighten-4 warning"><%= flash[:alert] %></h6>
  <% end %>

  <%= form_for @employee do |form| %>
    <div class="row customer-form__row customer-form__row--radio">
      <div class="col s12 l6 p0">
        <span style='margin: -12px;' class="customer-form__label--radio">Status:</span>
        <label for="employee_status_active">
          <input name="employee[status]" type="radio" id="employee_status_active" value="active" <%= @employee.status == 'active' ? 'checked' : '' %> />
          <span style="margin: 16px 0 0 20px;" class='black-text'>Ativo</span>
        </label>
        <label for="employee_status_vacation">
          <input name="employee[status]" type="radio" id="employee_status_vacation" value="vacation" <%= @employee.status == 'vacation' ? 'checked' : '' %> />
          <span class='black-text' style="margin-left: 20px;">Férias</span>
        </label>
        <label for="employee_status_deactivated">
          <input name="employee[status]" type="radio" id="employee_status_deactivated" value="deactivated" <%= @employee.status == 'deactivated' ? 'checked' : '' %> />
          <span class='black-text' style="margin-left: 20px;">Desativado</span>
        </label>
      </div>
    </div>

    <div class="row employee-form__row">
      <p class="input-field">
      <%= form.text_field :name, placeholder: "Nome" %>
      <%= form.label :name, "Nome" %>
      </p>
    </div>

    <div class="row employee-form__row">
      <p class="input-field">
      <%= form.text_field :phone, placeholder: "Telefone", data: {mask: '(99) 99999-9999'} %>
      <%= form.label :phone, "Telefone" %>
      </p>
    </div>

    <div class="row employee-form__row">
      <p class="input-field">
      <%= form.text_field :email, placeholder: "Email" %>
      <%= form.label :email, "Email" %>
      </p>
    </div>

    <div class="row employee-form__row">
      <p class="input-field">
      <%= form.text_field :birthdate, placeholder: "Data de Nascimento", class: "datepicker", value: @employee.birthdate&.strftime('%m/%d/%Y') %>
      <%= form.label :birthdate, "Data de Nascimento" %>
      </p>
    </div>

    <div class="row employee-form__row">
      <div class="input-field">
        <%= form.text_area :address, class: 'materialize-textarea' %>
        <%= form.label :address, 'Endereço' %>
      </div>
    </div>

    <div class="row employee-form__row" style='margin-top: -16px;'>
      <%= form.label :services, 'Serviços' %>
      <% Service.all.each do |service| %>
        <p>
        <label for="<%= "employee_#{service.id}" %>">
          <input <%= @services&.include?(service.id) ? 'checked' : '' %> id="<%= "employee_#{service.id}" %>" name="<%= "service_id[]" %>" type="checkbox" value="<%= service.id %>" />
          <span class='black-text'><%= service.name %></span>
        </label>
        </p>
      <% end %>
      </p>
    </div>

    <div class="center-align">
      <%= form.submit 'Alterar', class: 'red lighten-1 btn-large' %>
    </div>
  <% end %>
</div>


<script>
$(document).ready(function() {
  $(".datepicker").datepicker({
    i18n: {
      months: [
        "Janeiro",
        "Fevereiro",
        "Março",
        "Abril",
        "Maio",
        "Junho",
        "Julho",
        "Agosto",
        "Setembro",
        "Outubro",
        "Novembro",
        "Dezembro"
      ],
      monthsShort: [
        "Jan",
        "Fev",
        "Mar",
        "Abr",
        "Mai",
        "Jun",
        "Jul",
        "Ago",
        "Set",
        "Out",
        "Nov",
        "Dez"
      ],
      weekdays: [
        "Domingo",
        "Segunda",
        "Terça",
        "Quarta",
        "Quinta",
        "Sexta",
        "Sabádo"
      ],
      weekdaysShort: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sab"],
      weekdaysAbbrev: ["D", "S", "T", "Q", "Q", "S", "S"],
      today: "Hoje",
      clear: "Limpar",
      cancel: "Sair",
      done: "Confirmar",
      labelMonthNext: "Próximo mês",
      labelMonthPrev: "Mês anterior",
      labelMonthSelect: "Selecione um mês",
      labelYearSelect: "Selecione um ano",
      selectMonths: true,
      selectYears: 15
    },
    format: "dd/mm/yyyy",
    container: "body",
    minDate: new Date('01/01/1900'),
    yearRange: [1900, (new Date).getFullYear()]
  });
})

</script>

app/views/employees/index.html.erb
<div class="section no-pad-bot" id="index-banner">
  <h2 class="header center indigo-text text-darken-4">Funcionários</h2>
</div>

<% if admin?(current_user) %>
<div style="display: flex;">
  <a href="<%= new_employee_path %>"style="margin: auto; margin-bottom: 24px;" class="red lighten-1 btn">Novo Funcionário</a>
</div>
<% end %>

<div class="section no-pad-bot" id="index-banner">
  <h3 class="header center indigo-text text-darken-4">Ativos</h2>
</div>

<div class="collection">
  <% @employees.each do |employee|  %>
    <a href="<%= edit_employee_path(employee.id) if admin?(current_user) %>" class="collection-item"><%= employee.name %></a>
  <% end %>
</div>

<% if @vacation_employees.present? %>
  <div class="section no-pad-bot" id="index-banner">
    <h3 class="header center indigo-text text-darken-4">Férias</h2>
  </div>

  <div class="collection">
    <% @vacation_employees.each do |employee|  %>
      <a href="<%= edit_employee_path(employee.id) if admin?(current_user) %>" class="collection-item"><%= employee.name %></a>
    <% end %>
  </div>
<% end %>

<% if @deactivated_employees.present? %>
  <div class="section no-pad-bot" id="index-banner">
    <h3 class="header center indigo-text text-darken-4">Desativados</h2>
  </div>

  <div class="collection">
    <% @deactivated_employees.each do |employee|  %>
      <a href="<%= edit_employee_path(employee.id) if admin?(current_user) %>" class="collection-item"><%= employee.name %></a>
    <% end %>
  </div>
<% end %>

app/views/employees/new.html.erb
<div class="employee-form">

  <h3>Funcionário</h3>
  <% unless flash[:alert].empty? %>
    <h6 class="deep-orange-text text-darken-3 deep-orange lighten-4 warning"><%= flash[:alert] %></h6>
  <% end %>

  <%= form_for @employee do |form| %>

    <div class="row employee-form__row" style='margin-top: 48px;'>
      <p class="input-field">
        <%= form.text_field :name, placeholder: "Nome" %>
        <%= form.label :name, "Nome" %>
      </p>
    </div>

    <div class="row employee-form__row">
      <p class="input-field">
        <%= form.text_field :phone, placeholder: "Telefone", data: {mask: '(99) 99999-9999'} %>
        <%= form.label :phone, "Telefone" %>
      </p>
    </div>

    <div class="row employee-form__row">
      <p class="input-field">
        <%= form.text_field :email, placeholder: "Email" %>
        <%= form.label :email, "Email" %>
      </p>
    </div>

    <div class="row employee-form__row">
      <p class="input-field">
        <%= form.text_field :birthdate, placeholder: "Data de Nascimento", class: "datepicker" %>
        <%= form.label :birthdate, "Data de Nascimento" %>
      </p>
    </div>

    <div class="row employee-form__row">
      <p class="input-field">
        <%= form.text_field :document, placeholder: "Número do Documento" %>
        <%= form.label :document, "Número do documento" %>
      </p>
    </div>

    <div class="row employee-form__row">
      <p class="input-field">
        <%= form.text_field :address, placeholder: "Endereço" %>
        <%= form.label :address, "Endereço" %>
      </p>
    </div>

    <div class="row employee-form__row" style='margin-top: -16px;'>
      <%= form.label :services, 'Serviços' %>
      <% Service.all.each do |service| %>
        <p>
        <label for="<%= "employee_#{service.id}" %>">
          <input id="<%= "employee_#{service.id}" %>" name="<%= "service_id[]" %>" type="checkbox" value="<%= service.id %>" />
          <span class='black-text'><%= service.name %></span>
        </label>
        </p>
      <% end %>
      </p>
    </div>

    <div class="center-align">
      <%= form.submit 'Cadastrar', class: 'red lighten-1 btn-large' %>
    </div>
  <% end %>

</div>


<script>
  $(document).ready(function(){
    $(".datepicker").datepicker({
      i18n: {
        months: [
          "Janeiro",
          "Fevereiro",
          "Março",
          "Abril",
          "Maio",
          "Junho",
          "Julho",
          "Agosto",
          "Setembro",
          "Outubro",
          "Novembro",
          "Dezembro"
        ],
        monthsShort: [
          "Jan",
          "Fev",
          "Mar",
          "Abr",
          "Mai",
          "Jun",
          "Jul",
          "Ago",
          "Set",
          "Out",
          "Nov",
          "Dez"
        ],
        weekdays: [
          "Domingo",
          "Segunda",
          "Terça",
          "Quarta",
          "Quinta",
          "Sexta",
          "Sabádo"
        ],
        weekdaysShort: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sab"],
        weekdaysAbbrev: ["D", "S", "T", "Q", "Q", "S", "S"],
        today: "Hoje",
        clear: "Limpar",
        cancel: "Sair",
        done: "Confirmar",
        labelMonthNext: "Próximo mês",
        labelMonthPrev: "Mês anterior",
        labelMonthSelect: "Selecione um mês",
        labelYearSelect: "Selecione um ano",
        selectMonths: true,
        selectYears: 15
      },
      format: "dd/mm/yyyy",
      container: "body",
      minDate: new Date('01/01/1900'),
      yearRange: [1900, (new Date).getFullYear()]
    });
  });
</script>

app/views/employees/show.html.erb
<div class="employee-details">
  <div class="row">
    <div class="col s4">
      <h2><%= @employee.name %></h2>
    </div>

    <div class="col s4 right-align">
      <span class="customer-details__badge red">
        <%= I18n.t(@employee.status, scope: 'activerecord.attributes.employee.status') %>
      </span>
    </div>

    <div class="col s4 right-align">
      <% if current_user&.admin? %>
        <%= link_to 'Alterar', edit_employee_path(@employee), class: "indigo lighten-1 btn-small" %>
      <% end %>
    </div>
  </div>

  <h4>Telefone</h4>
  <p>
  <%= @employee.phone %>
  </p>
  <h4>Data de Nascimento</h4>
  <p>
  <%= @employee.birthdate %>
  </p>
  <h4>Endereço</h4>
  <p>
  <%= @employee.address %>
  </p>
  <h4>Serviços</h4>
  <ul>
    <% @employee.services.each do |service| %>
      <li> <%= service.name %>
    <% end %>
  </ul>
</div>