config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {:registrations => "registrations"}

  devise_scope :user do
    post "/register_user" => "registrations#create"
  end

  as :user do
    get "/register", to: "registrations#new", as: "register"
  end

  resources :customers
  resources :employees
  resources :services
  resources :attendances

  resources :rescue_requests do
    get 'answer', to: 'rescue_requests#answer'
  end

  root to: 'home#index'
  get '/dashboard', to: 'pages#dashboard'
  get '/search', to: 'customers#searchpage'
  post '/search', to: 'customers#search'
  get '/ban', to: 'pages#ban'
  post '/ban', to: 'pages#destroy_user'
  get '/schedule', to: 'attendances#schedule'

  post '/register_user', to: 'registrations#create'
end

app/controllers/home_controller.rb
# rubocop: disable Metrics/ClassLength
class HomeController < ApplicationController

  def index
  end
end
# rubocop: enable Metrics/ClassLength

app/views/home/index.html.erb
<div class="section no-pad-bot" id="index-banner">
  <div>
    <h1 class="header center indigo-text text-darken-4">Sistema de Agendamento</h1>
    <div class="row center">
      <div class="col s12 m4">
        <a href="<%= new_customer_path %>" class="home_button_find owner">
          <%= image_tag("cliente.jpg", :alt => "Cadastrar um Cliente") %>
          <span>
            Cadastrar um Cliente
          </span>
        </a>
      </div>
      <div class="col s12 m4">
        <a href="<%= employees_path %>" class="home_button_find owner">
          <%= image_tag("employee.jpg", :alt => "Cadastrar um funcinário") %>
          <span>
            Funcionários
          </span>
        </a>
      </div>
      <div class="col s12 m4">
        <a href="<%= services_path %>" class="home_button_find owner">
          <%= image_tag("servico.jpg", :alt => "Serviços") %>
          <span>
            Serviços
          </span>
        </a>
      </div>
    </div>
    <div class="col s12 m12">
      <a href="<%= schedule_path %>" class="home_button_find customer search">
        <%= image_tag("calendario.jpg", :alt => "Consultar Agenda") %>
        <span>
          <i class="material-icons">search</i>Consultar Agenda
        </span>
      </a>
    </div>
    <div class="col s12 m12">
      <a href="<%= search_path %>" class="home_button_find customer search">
        <%= image_tag("botao2.jpg", :alt => "Buscar Cliente") %>
        <span>
          <i class="material-icons">search</i> Buscar Cliente / Realizar agendamento
        </span>
      </a>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){
    $('.collapsible').collapsible();
  });
</script>