config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {:registrations => "registrations"}

  devise_scope :user do
    post "/register_user" => "registrations#create"
  end

  as :user do
    get "/register", to: "registrations#new", as: "register"
  end

  resources :customers
  resources :employees
  resources :services
  resources :attendances

  resources :rescue_requests do
    get 'answer', to: 'rescue_requests#answer'
  end

  root to: 'home#index'
  get '/dashboard', to: 'pages#dashboard'
  get '/search', to: 'customers#searchpage'
  post '/search', to: 'customers#search'
  get '/ban', to: 'pages#ban'
  post '/ban', to: 'pages#destroy_user'
  get '/schedule', to: 'attendances#schedule'

  post '/register_user', to: 'registrations#create'
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :customer
  belongs_to :employee
  belongs_to :service

  validate :employee_availability
  validate :end_after_start
  validate :employee_has_service

  def employee_availability
    attendances = Attendance.
      where(employee_id: employee_id).
      where('start_date BETWEEN ? and ?', start_date, end_date).
      where('end_date BETWEEN ? and ?', start_date, end_date)

    unless attendances.blank?
      errors.add(:base, 'Funcionário já possui agendamento nesse horário')
    end
  end

  def end_after_start
    if start_date >= end_date
      errors.add(:base, 'Horário de término tem que ser maior que o de início')
    end
  end

  def employee_has_service
    service_ids = Employee.find(employee_id).services.map(&:id)

    unless service_ids.include?(service_id)
      errors.add(:base, 'Este funcionário não presta este serviço')
    end
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: %i[ show edit update destroy ]

  # GET /attendances or /attendances.json
  def index
    @attendances = Attendance.all
  end

  # GET /attendances/1 or /attendances/1.json
  def show
    @employee = Employee.find_by(id: @attendance.employee_id).name
    @service = Service.find_by(id: @attendance.service_id).name
    @customer = Customer.find_by(id: @attendance.customer_id).name
  end

  # GET /attendances/new
  def new
    flash[:alert] = ''
    @attendance = Attendance.new
    @services = Service.all
    @employees = Employee.active.all
    @customer_id = params[:customer_id]

    date_params = params[:date] || DateTime.now.to_s
    @date = Time.parse(date_params)
  end

  # GET /attendances/1/edit
  def edit
    flash[:alert] = ''
    @services = Service.all
    @employees = Employee.active.all
  end

  # POST /attendances or /attendances.json
  def create
    start_at = DateTime.parse("#{attendance_params[:day]} #{attendance_params[:start_at]} utc-3")
    end_at = DateTime.parse("#{attendance_params[:day]} #{attendance_params[:end_at]} utc-3")

    @attendance = Attendance.new({
      title: attendance_params[:title],
      description: attendance_params[:description],
      start_date: start_at,
      end_date: end_at,
      customer_id: attendance_params[:customer_id],
      employee_id: attendance_params[:employee_id],
      service_id: attendance_params[:service_id]
    })

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to schedule_path(created: true), notice: "Attendance was successfully created." }
        format.json { render :show, status: :created, location: @attendance }
      else
        if @attendance.errors[:base].blank?
          flash[:alert] = 'Atendimento não pode ser salvo, horário indisponível'
        else
          flash[:alert] = @attendance.errors[:base].to_sentence
        end

        @services = Service.all
        @employees = Employee.all
        @customer_id = params[:customer_id]

        date_params = start_at.to_s || DateTime.now.to_s
        @date = Time.parse(date_params)

        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendances/1 or /attendances/1.json
  def update
    start_at = DateTime.parse("#{attendance_params[:day]} #{attendance_params[:start_at]} utc-3")
    end_at = DateTime.parse("#{attendance_params[:day]} #{attendance_params[:end_at]} utc-3")

    att = {
      title: attendance_params[:title],
      description: attendance_params[:description],
      start_date: start_at,
      end_date: end_at,
      customer_id: attendance_params[:customer_id],
      employee_id: attendance_params[:employee_id],
      service_id: attendance_params[:service_id]
    }

    @services = Service.all
    @employees = Employee.all

    respond_to do |format|
      if @attendance.update(att)
        format.html { redirect_to schedule_path }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1 or /attendances/1.json
  def destroy
    @attendance.destroy
    respond_to do |format|
      format.html { redirect_to schedule_path }
      format.json { head :no_content }
    end
  end

  def schedule
    flash[:alert] = params[:created].present? ? "Agendamento criado com sucesso!" : ''

    @attendances = Attendance.all.map do |attendance|
      employee = Employee.find_by(id: attendance.employee_id).name
      service = Service.find_by(id: attendance.service_id).name
      customer = Customer.find_by(id: attendance.customer_id).name

      {
        id: attendance.id,
        start: attendance.start_date,
        end: attendance.end_date,
        employee: employee,
        service: service,
        customer: customer,
        title: "#{customer} | #{employee} | #{service}"
      }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_attendance
    @attendance = Attendance.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def attendance_params
    params.require(:attendance).permit!
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_form.html.erb
<%= form_with(model: attendance) do |form| %>
  <% if attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
        <% attendance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.datetime_select :end_date %>
  </div>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.number_field :customer_id %>
  </div>

  <div class="field">
    <%= form.label :employee_id %>
    <%= form.number_field :employee_id %>
  </div>

  <div class="field">
    <%= form.label :service_id %>
    <%= form.number_field :service_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<div class="customer-form">

  <div style="display: flex; align-items: center; gap: 50px;">
    <h3>Alterar Agendamento</h3>
    <%= link_to 'Excluir', attendance_path(@attendance), :confirm => 'Confirma cancelamento deste agendamento?', :method => :delete, class: "btn red"  %>
  </div>
  <% unless flash[:alert].empty? %>
    <div class="deep-orange-text text-darken-3 deep-orange lighten-4 warning"><%= flash[:alert] %></div>
  <% end %>

  <%= form_for @attendance do |form| %>

    <div class="row customer-form__row">
      <p class="input-field">
        <%= form.text_field :description, placeholder: "Nome do Cliente", value: @attendance.customer.name %>
        <%= form.label :customer, "Nome do Cliente" %>
      </p>
    </div>

    <div class="row customer-form__row">
      <p class="input-field">
        <label for="attendance_service_id">Serviço</label><br>
        <%= collection_select(:attendance, :service_id, @services, :id, :name, {}, { class: 'input-field' }) %>
      </p>
    </div>

    <div class="row customer-form__row">
      <p class="input-field">
        <label for="attendance_employee_id">Funcionário</label><br>
        <%= collection_select(:attendance, :employee_id, @employees, :id, :name, {}, { class: 'input-field' }) %>
      </p>
    </div>

    <div class="row customer-form__row">
      <p class="input-field">
        <label for="day">Dia do Atendimento</label><br>
        <input type="text" name="attendance[day]" id="day" class="datepicker" value= <%= Date.parse(@attendance.start_date.to_date.to_s).strftime('%d/%m/%Y') %>>
      </p>
    </div>

    <div class="row customer-form__row">
      <p class="input-field">
      <label for="start_at">Horário de início</label><br>
      <input type="text" name="attendance[start_at]" id="start_at" class="timepicker" value="<%= Time.parse((@attendance.start_date - 3.hours).to_s(:time)).strftime('%H:%M') %>">
      </p>
    </div>

    <div class="row customer-form__row">
      <p class="input-field">
        <label for="end_at">Horário de término</label><br>
        <input type="text" name="attendance[end_at]" id="end_at" class="timepicker" value="<%= Time.parse((@attendance.end_date - 3.hours).to_s(:time)).strftime('%H:%M') %>" >
      </p>
    </div>

    <div class="row customer-form__row">
      <p class="input-field">
        <%= form.text_field :description, placeholder: "Descrição" %>
        <%= form.label :description, "Descrição", value: @attendance.description || ''  %>
      </p>
    </div>

    <%= form.hidden_field :customer_id, { value: @attendance.customer_id } %>
    <%= form.hidden_field :date, { value: params[:date] } %>

    <div class="center-align">
      <%= form.submit 'Alterar', class: 'red lighten-1 btn-large' %>
    </div>
  <% end %>
</div>

app/views/attendances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attendances</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Customer</th>
      <th>Employee</th>
      <th>Service</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendances.sort_by{|x| x.start_date}.each do |attendance| %>
      <tr>
        <td><%= attendance.title %></td>
        <td><%= attendance.description %></td>
        <td><%= attendance.start_date.strftime("%d/%m/%y %I:%M %P") %></td>
        <td><%= attendance.end_date.strftime("%d/%m/%y %I:%M %P") %></td>
        <td><%= Customer.find_by(id: attendance.customer_id).name %></td>
        <td><%= Employee.find_by(id: attendance.employee_id).name %></td>
        <td><%= Service.find_by(id: attendance.service_id).name %></td>
        <td><%= link_to 'Visualizar', attendance %></td>
        <td><%= link_to 'Alterar', edit_attendance_path(attendance) %></td>
        <td><%= link_to 'Apagar', attendance, method: :delete, data: { confirm: 'Você quer mesmo apagar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo agendamento', new_attendance_path %>

app/views/attendances/new.html.erb
<div class="customer-form">

  <h3>Novo Agendamento</h3>
  <% unless flash[:alert].empty? %>
    <div class="deep-orange-text text-darken-3 deep-orange lighten-4 warning"><%= flash[:alert] %></div>
  <% end %>

  <%= form_for @attendance, url: attendances_path(customer_id: @customer_id) do |form| %>

    <div class="row customer-form__row">
      <p class="input-field">
        <%= form.text_field :description, placeholder: "Nome do Cliente", value: Customer.find(params["customer_id"]).name %>
        <%= form.label :customer, "Nome do Cliente" %>
      </p>
    </div>

    <div class="row customer-form__row">
      <p class="input-field">
        <label for="attendance_service_id">Serviço</label><br>
        <%= collection_select(:attendance, :service_id, @services, :id, :name, {}, { class: 'input-field' }) %>
      </p>
    </div>

    <div class="row customer-form__row">
      <p class="input-field">
        <label for="attendance_employee_id">Funcionário</label><br>
        <%= collection_select(:attendance, :employee_id, @employees, :id, :name, {}, { class: 'input-field' }) %>
      </p>
    </div>

    <div class="row customer-form__row">
      <p class="input-field">
        <label for="day">Dia do Atendimento</label><br>
        <input type="text" name="attendance[day]" id="day" class="datepicker" value="<%= Date.parse(@date.to_date.to_s).strftime("%d/%m/%Y") %>">
      </p>
    </div>

    <div class="row customer-form__row">
      <p class="input-field">
      <label for="start_at">Horário de início</label><br>
      <input type="text" name="attendance[start_at]" id="start_at" class="timepicker" value="<%= Time.parse(@date.to_s(:time)).strftime("%H:%M") %>">
      </p>
    </div>

    <div class="row customer-form__row">
      <p class="input-field">
        <label for="end_at">Horário de término</label><br>
        <input type="text" name="attendance[end_at]" id="end_at" class="timepicker" value="<%= (@date + 1.hour).to_s(:time) %>" >
      </p>
    </div>

    <div class="row customer-form__row">
      <p class="input-field">
        <%= form.text_field :description, placeholder: "Descrição" %>
        <%= form.label :description, "Descrição", value: @attendance.description || ''  %>
      </p>
    </div>

    <%= form.hidden_field :customer_id, { value: params[:customer_id] } %>
    <%= form.hidden_field :date, { value: params[:date] } %>

    <div class="center-align">
      <%= form.submit 'Agendar', class: 'red lighten-1 btn-large' %>
    </div>
  <% end %>
</div>

app/views/attendances/schedule.html.erb
<% unless flash[:alert].empty? %>
  <h6 class="card-panel teal lighten-2 white-text"><%= flash[:alert] %></h6>
<% end %>

<div style='height: 850px;'>
  <div id="calendar"></div>
</div>


<script>
  $(document).ready(function() {
    var calendarEl = document.getElementById('calendar');

    const customer_id = document.location.search.split("?")[1]

    const initialView = customer_id ? 'timeGridWeek' : 'timeGridDay' 

    new Calendar(calendarEl, {
      plugins: [ dayGridPlugin, timeGridPlugin, listPlugin, interactorPlugin ],
      locales: [brLocale],
      locale: 'pt-br',
      initialView,
      height: '100%',
      headerToolbar: {
        left: 'prev,next today',
        center: 'title',
        right: 'dayGridMonth,timeGridWeek,timeGridDay'
      },
      dateClick: e => {
        if(customer_id) window.location.href = `/attendances/new?date=${e.dateStr}&${customer_id}`
      },
      eventClick: e => {
        window.location.href = `/attendances/${e.event._def.publicId}/edit`
      },
      events: <%= @attendances.to_json.html_safe  %>
  }).render()
  });
</script>

app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<p>

<p>
  <strong>Cliente:</strong>
  <%= @customer %>
</p>

<p>
  <strong>Funcionário:</strong>
  <%= @employee %>
</p>

<p>
  <strong>Serviço:</strong>
  <%= @service %>
</p>

<p>
  <strong>Data de início:</strong>
  <%= @attendance.start_date.strftime("%d/%m/%y %I:%M %P") %>
</p>

<p>
  <strong>Data de término:</strong>
  <%= @attendance.end_date.strftime("%d/%m/%y %I:%M %P") %>
</p>

<p>
<strong>Descrição:</strong>
<%= @attendance.description %>
</p>

<%= link_to 'Alterar agendamento', edit_attendance_path(@attendance) %> |
<%= link_to 'Ver lista de agendamentos', attendances_path %> |
<%= link_to 'Ver agenda completa', schedule_path %>